"""
This type stub file was generated by pyright.
"""

import ctypes
import comtypes
import comtypes.client
import comtypes.client.dynamic
from ctypes import HRESULT, OleDLL, POINTER, _Pointer, byref, c_void_p
from ctypes.wintypes import DWORD, LPVOID
from typing import Any, Optional, TYPE_CHECKING, Type
from comtypes import GUID, IUnknown, STDMETHOD, hints
from comtypes.automation import IDispatch
from comtypes.GUID import REFCLSID

if TYPE_CHECKING:
    ...
class IClassFactory(IUnknown):
    _iid_ = ...
    _methods_ = ...
    def CreateInstance(self, punkouter: Optional[Type[_Pointer[IUnknown]]] = ..., interface: Optional[Type[IUnknown]] = ..., dynamic: bool = ...) -> Any:
        ...
    
    if TYPE_CHECKING:
        def LockServer(self, fLock: int) -> hints.Hresult:
            ...
        


ACTIVEOBJECT_STRONG = ...
ACTIVEOBJECT_WEAK = ...
_oleaut32 = ...
_RegisterActiveObject = ...
_RevokeActiveObject = ...
def RegisterActiveObject(comobj: comtypes.COMObject, weak: bool = ...) -> int:
    ...

def RevokeActiveObject(handle: int) -> None:
    ...

