"""
This type stub file was generated by pyright.
"""

from ctypes import c_void_p

class _coclass_meta(type):
    def __new__(cls, name, bases, namespace): # -> Self | _coclass_pointer_meta | _coclass_meta:
        ...
    


class _coclass_pointer_meta(type(c_void_p), _coclass_meta):
    ...


