"""
This type stub file was generated by pyright.
"""

"""Consolidation of numpy support utilities."""
is_64bits = ...
class Interop:
    """Class encapsulating all the functionality necessary to allow interop of
    comtypes with numpy. Needs to be enabled with the "enable()" method.
    """
    def __init__(self) -> None:
        ...
    
    def isndarray(self, value): # -> bool:
        """Check if a value is an ndarray.

        This cannot succeed if numpy is not available.

        """
        ...
    
    def isdatetime64(self, value): # -> bool:
        """Check if a value is a datetime64.

        This cannot succeed if datetime64 is not available.

        """
        ...
    
    @property
    def numpy(self): # -> Any:
        """The numpy package."""
        ...
    
    def enable(self): # -> None:
        """Enables numpy/comtypes interop."""
        ...
    


interop = ...
__all__ = ["interop"]
