"""
This type stub file was generated by pyright.
"""

import contextlib

@contextlib.contextmanager
def chdir(path): # -> Generator[None, Any, None]:
    """Context manager to change the current working directory."""
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
