"""
This type stub file was generated by pyright.
"""

import logging

_kernel32 = ...
_OutputDebugStringA = ...
_OutputDebugStringW = ...
class NTDebugHandler(logging.Handler):
    def emit(self, record, writeA=..., writeW=...): # -> None:
        ...
    


def setup_logging(*pathnames): # -> None:
    ...

