"""
This type stub file was generated by pyright.
"""

import comtypes
from typing import TYPE_CHECKING, TypeVar

if TYPE_CHECKING:
    _CT = TypeVar("_CT", bound=comtypes._CData)
_safearray_type_cache = ...
class _SafeArrayAsNdArrayContextManager:
    """Context manager allowing safe arrays to be extracted as ndarrays.

    This is thread-safe.

    Example
    -------

    This works in python >= 2.5
    >>> with safearray_as_ndarray:
    >>>     my_arr = com_object.AsSafeArray
    >>> type(my_arr)
    numpy.ndarray

    """
    thread_local = ...
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    
    def __bool__(self): # -> bool:
        """True if context manager is currently entered on given thread."""
        ...
    
    __nonzero__ = ...


safearray_as_ndarray = ...
