"""
This type stub file was generated by pyright.
"""

from ctypes import Array as _CArrayType, c_ubyte
from typing import TYPE_CHECKING, Tuple
from comtypes import IUnknown

if TYPE_CHECKING:
    ...
class ISequentialStream(IUnknown):
    """Defines methods for the stream objects in sequence."""
    _iid_ = ...
    _idlflags_ = ...
    _methods_ = ...
    def RemoteRead(self, cb: int) -> Tuple[_CArrayType[c_ubyte], int]:
        """Reads a specified number of bytes from the stream object into memory
        starting at the current seek pointer.
        """
        ...
    
    if TYPE_CHECKING:
        def RemoteWrite(self, pv: _CArrayType[c_ubyte], cb: int) -> int:
            """Writes a specified number of bytes into the stream object starting at
            the current seek pointer.
            """
            ...
        


__known_symbols__ = ...
