"""
This type stub file was generated by pyright.
"""

from ctypes import *

"""This module defines the funtions byref_at(cobj, offset)
and cast_field(struct, fieldname, fieldtype).
"""
def byref_at(obj, offset, _byref=..., _c_void_p_from_address=..., _byref_pointer_offset=...):
    """byref_at(cobj, offset) behaves similar this C code:

        (((char *)&obj) + offset)

    In other words, the returned 'pointer' points to the address of
    'cobj' + 'offset'.  'offset' is in units of bytes.
    """
    ...

def cast_field(struct, fieldname, fieldtype, offset=..., _POINTER=..., _byref_at=..., _byref=..., _divmod=..., _sizeof=...):
    """cast_field(struct, fieldname, fieldtype)

    Return the contents of a struct field as it it were of type
    'fieldtype'.
    """
    ...

__all__ = ["byref_at", "cast_field"]
