"""
This type stub file was generated by pyright.
"""

from typing import Type
from comtypes import patcher

_all_slice = ...
def case_insensitive(p: Type) -> None:
    @patcher.Patch(p)
    class CaseInsensitive:
        ...
    
    

def reference_fix(pp: Type) -> None:
    @patcher.Patch(pp)
    class ReferenceFix:
        ...
    
    

def sized(itf: Type) -> None:
    @patcher.Patch(itf)
    class _:
        ...
    
    

def callable_and_subscriptable(itf: Type) -> None:
    @patcher.Patch(itf)
    class _:
        ...
    
    

def iterator(itf: Type) -> None:
    @patcher.Patch(itf)
    class _:
        ...
    
    

