"""
This type stub file was generated by pyright.
"""

from ctypes import _SimpleCData
from typing import Any, Callable, TYPE_CHECKING
from comtypes import hints

if TYPE_CHECKING:
    ...
_oleaut32 = ...
_SysFreeString = ...
class BSTR(_SimpleCData):
    """The windows BSTR data type"""
    _type_ = ...
    _needsfree = ...
    def __repr__(self) -> str:
        ...
    
    def __ctypes_from_outparam__(self) -> Any:
        ...
    
    def __del__(self, _free: Callable[[BSTR], Any] = ...) -> None:
        ...
    
    @classmethod
    def from_param(cls, value: Any) -> hints.Self:
        """Convert into a foreign function call parameter."""
        ...
    


