from enum import IntFlag

from . import _1F001332_1A57_4934_BE31_AFFC99F4EE0A_0_1_0 as __wrapper_module__
from . _1F001332_1A57_4934_BE31_AFFC99F4EE0A_0_1_0 import (
    tagVersionedStream, _ULARGE_INTEGER, tagSAFEARRAYBOUND,
    tagTLIBATTR, tagCADATE, IPortableDevicePropVariantCollection,
    IPortableDeviceServiceMethods, tagCAFILETIME, dispid, ULONG_PTR,
    tagFUNCDESC, tagCACLIPDATA, IDispatch, tagVARKIND, tagTYPEATTR,
    IPortableDeviceManager, _wireSAFEARRAY, IPortableDeviceContent,
    __MIDL_IOleAutomationTypes_0004, tagBLOB, tagCALPSTR, tagELEMDESC,
    IPortableDeviceValues, IEnumPortableDeviceObjectIDs, SCODE,
    _SHORT_SIZEDARR, tagCAC, tagCACLSID, tagCADBL, STRING,
    _wireBRECORD, wirePSAFEARRAY, PortableDeviceService, tagBSTRBLOB,
    VARIANT_BOOL, wireSNB, _FILETIME, tagTYPEDESC,
    IPortableDeviceService, _wireSAFEARR_UNKNOWN, _wireSAFEARR_BSTR,
    IPortableDeviceResources, PortableDeviceServiceFTM,
    _wireSAFEARR_HAVEIID, tagCALPWSTR, ISequentialStream,
    tagCAPROPVARIANT, __MIDL_IOleAutomationTypes_0001, tagCABSTRBLOB,
    PortableDeviceManager, tagVARDESC, _wireSAFEARRAY_UNION,
    __MIDL___MIDL_itf_PortableDeviceApi_0001_0000_0001,
    IPropertyStore, IPortableDeviceWebControl, _wireSAFEARR_DISPATCH,
    IPortableDeviceProperties, PortableDeviceFTM, tagSTATSTG, _lcid,
    tagCAI, tagCAFLT, _wireSAFEARR_VARIANT,
    IPortableDeviceServiceCapabilities, tagPARAMDESCEX, tagCAL,
    IPortableDeviceDispatchFactory, PortableDevice, _wireVARIANT,
    WSTRING, ITypeLib, COMMETHOD, tagCACY, helpstring,
    _HYPER_SIZEDARR, _LARGE_INTEGER, tagPARAMDESC, IPortableDevice,
    tagCLIPDATA, IPortableDeviceValuesCollection,
    _wireSAFEARR_BRECORD, ITypeComp, IUnknown, CoClass, VARIANT,
    __MIDL_IOleAutomationTypes_0005, tagCASCODE, _FLAGGED_WORD_BLOB,
    IPortableDeviceServiceMethodCallback, tagCABSTR, DWORD,
    PortableDeviceDispatchFactory, __MIDL_IOleAutomationTypes_0006,
    GUID, tagCAH, IPortableDeviceCapabilities,
    IPortableDeviceContent2, tagCALLCONV, Library, _BYTE_SIZEDARR,
    tagSYSKIND, tagINVOKEKIND, PortableDeviceWebControl, tagTYPEKIND,
    HRESULT, IRecordInfo, IStream, ITypeInfo, tagCAUL,
    tag_inner_PROPVARIANT, tagCAUI, typelib_path, tagCABOOL,
    tagARRAYDESC, tagCAUB, _tagpropertykey, _check_version,
    _LONG_SIZEDARR, tagCAUH, tagFUNCKIND, tagDESCKIND, tagRemSNB,
    tagIDLDESC, IPortableDeviceKeyCollection,
    IPortableDeviceEventCallback, BSTR, IStorage, DECIMAL,
    IEnumSTATSTG
)


__all__ = [
    'IPortableDevicePropVariantCollection', 'IPortableDeviceManager',
    '_wireSAFEARRAY', 'tagBLOB', 'tagCALPSTR', 'tagCAC', 'tagCACLSID',
    'tagCADBL', '_wireBRECORD', 'wirePSAFEARRAY',
    'PortableDeviceService', 'IPortableDeviceService',
    'PortableDeviceServiceFTM', '_wireSAFEARR_HAVEIID',
    'tagCAPROPVARIANT', 'tagCABSTRBLOB', 'PortableDeviceManager',
    '__MIDL___MIDL_itf_PortableDeviceApi_0001_0000_0001',
    'IPropertyStore', '_wireSAFEARR_DISPATCH', 'tagCAL',
    'PortableDevice', 'tagCACY', 'IPortableDeviceValuesCollection',
    '_wireSAFEARR_BRECORD', 'IPortableDeviceServiceMethodCallback',
    'PortableDeviceDispatchFactory', 'tagCAH',
    'IPortableDeviceCapabilities', 'Library', 'tagCAUL',
    'tag_inner_PROPVARIANT', 'tagCAUI', 'tagCAUB', '_tagpropertykey',
    '_LONG_SIZEDARR', 'tagCAUH', 'IPortableDeviceKeyCollection',
    'IEnumSTATSTG', 'IPortableDeviceEventCallback', 'IStorage',
    'tagVersionedStream', 'tagCADATE',
    'IPortableDeviceServiceMethods', 'tagCAFILETIME', 'tagCACLIPDATA',
    'IPortableDeviceContent', '__MIDL_IOleAutomationTypes_0004',
    'IPortableDeviceValues', 'IEnumPortableDeviceObjectIDs',
    '_SHORT_SIZEDARR', 'tagBSTRBLOB', 'wireSNB',
    '_wireSAFEARR_UNKNOWN', '_wireSAFEARR_BSTR',
    'IPortableDeviceResources', '__MIDL_IOleAutomationTypes_0001',
    '_wireSAFEARRAY_UNION', 'IPortableDeviceWebControl',
    'IPortableDeviceProperties', 'PortableDeviceFTM', 'tagSTATSTG',
    'tagCAI', 'tagCAFLT', '_wireSAFEARR_VARIANT',
    'IPortableDeviceServiceCapabilities',
    'IPortableDeviceDispatchFactory', '_wireVARIANT',
    '_HYPER_SIZEDARR', 'IPortableDevice', 'tagCLIPDATA',
    '__MIDL_IOleAutomationTypes_0005', 'tagCASCODE',
    '_FLAGGED_WORD_BLOB', 'tagCABSTR',
    '__MIDL_IOleAutomationTypes_0006', 'IPortableDeviceContent2',
    '_BYTE_SIZEDARR', 'PortableDeviceWebControl', 'IStream',
    'typelib_path', 'tagCABOOL', 'tagRemSNB', 'tagCALPWSTR'
]

