from enum import IntFlag

from . import _2B00BA2F_E750_4BEB_9235_97142EDE1D3E_0_1_0 as __wrapper_module__
from . _2B00BA2F_E750_4BEB_9235_97142EDE1D3E_0_1_0 import (
    tagVersionedStream,
    __MIDL___MIDL_itf_PortableDeviceTypes_0003_0017_0001,
    _ULARGE_INTEGER, tagTLIBATTR, tagCADATE, tagSAFEARRAYBOUND,
    IPortableDevicePropVariantCollection, tagCAFILETIME, tagFUNCDESC,
    ULONG_PTR, tagCACLIPDATA, PortableDevicePropVariantCollection,
    IDispatch, tagVARKIND, tagTYPEATTR, _wireSAFEARRAY, tagELEMDESC,
    __MIDL_IOleAutomationTypes_0004, tagBLOB, tagCALPSTR,
    PortableDeviceValuesCollection, IPortableDeviceValues, SCODE,
    _SHORT_SIZEDARR, tagCAC, tagCACLSID, tagCADBL, STRING,
    _wireBRECORD, wirePSAFEARRAY, tagBSTRBLOB, VARIANT_BOOL, wireSNB,
    _FILETIME, tagTYPEDESC, _wireSAFEARR_BSTR, _wireSAFEARR_UNKNOWN,
    WpdSerializer, _wireSAFEARR_HAVEIID, tagCALPWSTR,
    ISequentialStream, PortableDeviceKeyCollection, tagCAPROPVARIANT,
    PortableDeviceValues, tagCABSTRBLOB,
    __MIDL_IOleAutomationTypes_0001, tagVARDESC, _wireSAFEARRAY_UNION,
    IPropertyStore, _wireSAFEARR_DISPATCH, tagSTATSTG, _lcid, tagCAI,
    tagCAFLT, _wireSAFEARR_VARIANT, tagPARAMDESCEX, tagCAL,
    _wireVARIANT, WSTRING, ITypeLib, COMMETHOD, tagCACY,
    _HYPER_SIZEDARR, _LARGE_INTEGER, tagPARAMDESC, tagCLIPDATA,
    IPortableDeviceValuesCollection, _wireSAFEARR_BRECORD, ITypeComp,
    IUnknown, CoClass, VARIANT, __MIDL_IOleAutomationTypes_0005,
    tagCASCODE, _FLAGGED_WORD_BLOB, IWpdSerializer, tagCABSTR, DWORD,
    GUID, __MIDL_IOleAutomationTypes_0006, tagCALLCONV, tagCAH,
    tagSYSKIND, _BYTE_SIZEDARR, Library, tagINVOKEKIND, tagTYPEKIND,
    HRESULT, IRecordInfo, IStream, ITypeInfo, tagCAUL,
    tag_inner_PROPVARIANT, typelib_path, tagCAUI, tagCABOOL,
    tagARRAYDESC, tagCAUB, _tagpropertykey, _check_version,
    _LONG_SIZEDARR, tagCAUH, tagFUNCKIND, tagDESCKIND, tagRemSNB,
    tagIDLDESC, IPortableDeviceKeyCollection, BSTR, IStorage, DECIMAL,
    IEnumSTATSTG
)


__all__ = [
    '_wireSAFEARR_VARIANT', 'tagVersionedStream',
    '__MIDL___MIDL_itf_PortableDeviceTypes_0003_0017_0001',
    'tagCADATE', 'tagCAL', '_wireVARIANT',
    'IPortableDevicePropVariantCollection', 'tagCAFILETIME',
    'tagCACY', '_HYPER_SIZEDARR', 'tagCACLIPDATA',
    'PortableDevicePropVariantCollection', '_wireSAFEARRAY',
    'tagCLIPDATA', 'IPortableDeviceValuesCollection', 'tagBLOB',
    'tagCALPSTR', '__MIDL_IOleAutomationTypes_0004',
    '_wireSAFEARR_BRECORD', 'PortableDeviceValuesCollection',
    'IPortableDeviceValues', '_SHORT_SIZEDARR', 'tagCAC',
    'tagCACLSID', 'tagCADBL', '__MIDL_IOleAutomationTypes_0005',
    'tagCASCODE', '_FLAGGED_WORD_BLOB', 'IWpdSerializer',
    '_wireBRECORD', 'tagCABSTR', 'wirePSAFEARRAY',
    '__MIDL_IOleAutomationTypes_0006', 'tagBSTRBLOB', 'tagCAH',
    '_BYTE_SIZEDARR', 'Library', 'wireSNB', 'IStream',
    '_wireSAFEARR_BSTR', '_wireSAFEARR_UNKNOWN', 'WpdSerializer',
    'tagCAFLT', '_wireSAFEARR_HAVEIID', 'tagCAUL',
    'PortableDeviceKeyCollection', 'tagCAPROPVARIANT',
    'tag_inner_PROPVARIANT', 'typelib_path', 'PortableDeviceValues',
    'tagCABSTRBLOB', '_wireSAFEARRAY_UNION',
    '__MIDL_IOleAutomationTypes_0001', '_tagpropertykey', 'tagCAUB',
    'tagCAUI', '_LONG_SIZEDARR', 'tagCAUH', 'tagRemSNB',
    'IPropertyStore', '_wireSAFEARR_DISPATCH',
    'IPortableDeviceKeyCollection', 'tagSTATSTG', 'IEnumSTATSTG',
    'tagCABOOL', 'tagCAI', 'IStorage', 'tagCALPWSTR'
]

