from enum import IntFlag

from . import _1F001332_1A57_4934_BE31_AFFC99F4EE0A_0_1_0 as __wrapper_module__
from . _1F001332_1A57_4934_BE31_AFFC99F4EE0A_0_1_0 import (
    tagCACY, _HYPER_SIZEDARR, IPortableDeviceResources, _FILETIME,
    tagIDLDESC, IPortableDeviceKeyCollection, DECIMAL,
    _ULARGE_INTEGER, ITypeLib, _LARGE_INTEGER, VARIANT_BOOL,
    _wireSAFEARR_HAVEIID, PortableDeviceDispatchFactory, ITypeInfo,
    PortableDeviceManager, _check_version, Library,
    PortableDeviceServiceFTM, dispid, IPortableDeviceManager,
    IEnumSTATSTG, GUID, tagTLIBATTR, tagCAC, PortableDeviceService,
    _wireSAFEARR_DISPATCH, tagCAH, tagCAPROPVARIANT, tagTYPEKIND,
    tagCAUB, tagCALLCONV, _lcid, STRING, IStream,
    __MIDL___MIDL_itf_PortableDeviceApi_0001_0000_0001, tagCACLIPDATA,
    tagDESCKIND, IPortableDeviceServiceMethods, tagCALPWSTR,
    IPortableDeviceContent2, _LONG_SIZEDARR,
    IPortableDeviceServiceMethodCallback, tagFUNCKIND, COMMETHOD,
    PortableDevice, tagCABSTRBLOB, IPortableDeviceWebControl,
    _wireSAFEARRAY, _wireBRECORD, tagCALPSTR, _BYTE_SIZEDARR, WSTRING,
    ITypeComp, _wireSAFEARR_BSTR, _wireSAFEARRAY_UNION,
    _tagpropertykey, tagCABOOL, __MIDL_IOleAutomationTypes_0005,
    PortableDeviceFTM, IRecordInfo,
    IPortableDeviceServiceCapabilities, tagPARAMDESCEX, tagTYPEATTR,
    helpstring, _wireSAFEARR_VARIANT, IEnumPortableDeviceObjectIDs,
    tagSTATSTG, SCODE, HRESULT, ULONG_PTR,
    __MIDL_IOleAutomationTypes_0001, tagCAFLT, IStorage, typelib_path,
    IPortableDeviceValues, tagARRAYDESC, tagCLIPDATA, tagINVOKEKIND,
    tagCAUH, IPortableDevice, IPortableDeviceProperties, tagCADBL,
    ISequentialStream, tagCAFILETIME, BSTR, tagCAI, tagVARKIND,
    tagVARDESC, _SHORT_SIZEDARR, IPortableDeviceService,
    IPortableDeviceDispatchFactory, IDispatch, tagCADATE,
    tagSAFEARRAYBOUND, tagCABSTR, IPropertyStore, wireSNB,
    __MIDL_IOleAutomationTypes_0006, tagTYPEDESC, tagCAL,
    tagVersionedStream, _wireVARIANT, PortableDeviceWebControl,
    IPortableDeviceContent, VARIANT, tagCASCODE,
    tag_inner_PROPVARIANT, DWORD, IPortableDeviceEventCallback,
    IUnknown, tagCAUL, tagBLOB, _wireSAFEARR_BRECORD,
    IPortableDeviceValuesCollection, tagBSTRBLOB,
    IPortableDeviceCapabilities, tagPARAMDESC, wirePSAFEARRAY,
    tagFUNCDESC, tagELEMDESC, tagRemSNB, tagCACLSID, tagCAUI,
    _FLAGGED_WORD_BLOB, _wireSAFEARR_UNKNOWN, CoClass,
    __MIDL_IOleAutomationTypes_0004, tagSYSKIND,
    IPortableDevicePropVariantCollection
)


__all__ = [
    'IPortableDeviceKeyCollection', '_wireSAFEARR_HAVEIID',
    'PortableDeviceDispatchFactory', 'Library', 'IEnumSTATSTG',
    'tagCAC', 'PortableDeviceService', 'tagCALPWSTR', 'tagCABSTRBLOB',
    '_wireSAFEARRAY', '_wireSAFEARR_BSTR', '_wireSAFEARRAY_UNION',
    '_tagpropertykey', 'tagCABOOL', '__MIDL_IOleAutomationTypes_0005',
    'IPortableDeviceServiceCapabilities', '_wireSAFEARR_VARIANT',
    'tagSTATSTG', '__MIDL_IOleAutomationTypes_0001', 'typelib_path',
    'tagCAUH', 'IPortableDevice', 'IPortableDeviceProperties',
    'tagCAI', 'IPortableDeviceService', 'tagCAL', '_wireVARIANT',
    'PortableDeviceWebControl', 'tagCAUL', 'tagBLOB',
    '_wireSAFEARR_BRECORD', 'IPortableDeviceCapabilities',
    'tagRemSNB', 'tagCACLSID', '_FLAGGED_WORD_BLOB',
    '__MIDL_IOleAutomationTypes_0004', 'tagCACY', '_HYPER_SIZEDARR',
    'IPortableDeviceResources', 'PortableDeviceManager',
    'PortableDeviceServiceFTM', 'IPortableDeviceManager',
    '_wireSAFEARR_DISPATCH', 'tagCAH', 'tagCAPROPVARIANT', 'tagCAUB',
    'IStream', '__MIDL___MIDL_itf_PortableDeviceApi_0001_0000_0001',
    'tagCACLIPDATA', 'IPortableDevicePropVariantCollection',
    'IPortableDeviceServiceMethods', 'IPortableDeviceContent2',
    '_LONG_SIZEDARR', 'IPortableDeviceServiceMethodCallback',
    'PortableDevice', 'IPortableDeviceWebControl', '_wireBRECORD',
    'tagCALPSTR', 'PortableDeviceFTM', 'IEnumPortableDeviceObjectIDs',
    'tagCAFLT', 'IStorage', 'IPortableDeviceValues', 'tagCLIPDATA',
    'tagCADBL', 'tagCAFILETIME', '_SHORT_SIZEDARR',
    'IPortableDeviceDispatchFactory', 'tagCADATE', 'tagCABSTR',
    'IPropertyStore', 'wireSNB', '__MIDL_IOleAutomationTypes_0006',
    'tagVersionedStream', 'IPortableDeviceContent', 'tagCASCODE',
    'tag_inner_PROPVARIANT', 'IPortableDeviceEventCallback',
    'IPortableDeviceValuesCollection', 'tagBSTRBLOB',
    'wirePSAFEARRAY', 'tagCAUI', '_wireSAFEARR_UNKNOWN',
    '_BYTE_SIZEDARR'
]

