"""
This type stub file was generated by pyright.
"""

import ctypes
import logging
import comtypes.gen
from comtypes import automation
from comtypes.client import dynamic, lazybind
from comtypes.client._code_cache import _find_gen_dir
from comtypes.client._constants import Constants
from comtypes.client._events import GetEvents, PumpEvents, ShowEvents
from comtypes.client._generate import GetModule
from comtypes.client._managing import GetBestInterface, _manage, wrap_outparam
from comtypes.hresult import *
from comtypes.client._activeobj import GetActiveObject
from comtypes.client._create import CoGetObject, CreateObject, GetClassObject

"""comtypes.client - High level client level COM support package."""
gen_dir = ...
logger = ...
wrap = ...
__all__ = ["CreateObject", "GetActiveObject", "CoGetObject", "GetEvents", "ShowEvents", "PumpEvents", "GetModule", "GetClassObject"]
