"""
This type stub file was generated by pyright.
"""

"""comtypes.client._code_cache helper module.

The main function is _find_gen_dir(), which on-demand creates the
comtypes.gen package and returns a directory where generated code can
be written to.
"""
logger = ...
_shell32 = ...
SHGetSpecialFolderPath = ...
CSIDL_APPDATA = ...
