"""
This type stub file was generated by pyright.
"""

class _frozen_attr_dict(dict):
    __slots__ = ...
    def __getattr__(self, name):
        ...
    
    def __setitem__(self, key, value):
        ...
    
    def __delitem__(self, name):
        ...
    
    def __ior__(self, other):
        ...
    
    def clear(self):
        ...
    
    def pop(self, key, default=...):
        ...
    
    def popitem(self, last=...):
        ...
    
    def setdefault(self, key, default=...):
        ...
    


class Constants:
    """This class loads the type library from the supplied object,
    then exposes constants and enumerations in the type library
    as attributes.

    Examples:
        >>> c = Constants('scrrun.dll')  # load `Scripting` consts, enums, and alias
        >>> c.IOMode.ForReading  # returns enumeration member value
        1
        >>> c.ForReading  # returns constant value
        1
        >>> c.FileAttribute.Normal
        0
        >>> c.Normal
        0
        >>> 'ForReading' in c.consts  # as is `key in dict`
        True
        >>> 'IOMode' in c.enums  # as is `key in dict`
        True
        >>> 'ForReading' in c.IOMode  # as is `key in dict`
        True
        >>> 'FileAttribute' in c.enums  # It's alias of `__MIDL___MIDL...`
        False
        >>> 'FileAttribute' in c.alias  # as is `key in dict`
        True
    """
    __slots__ = ...
    def __init__(self, obj) -> None:
        ...
    
    def __getattr__(self, name):
        ...
    


