"""
This type stub file was generated by pyright.
"""

from typing import Any

logger = ...
def wrap_outparam(punk: Any) -> Any:
    ...

def GetBestInterface(punk: Any) -> Any:
    """Try to QueryInterface a COM pointer to the 'most useful'
    interface.

    Get type information for the provided object, either via
    IDispatch.GetTypeInfo(), or via IProvideClassInfo.GetClassInfo().
    Generate a wrapper module for the typelib, and QI for the
    interface found.
    """
    ...

