"""
This type stub file was generated by pyright.
"""

class FuncDesc:
    """Stores important FUNCDESC properties by copying them from a
    real FUNCDESC instance.
    """
    def __init__(self, **kw) -> None:
        ...
    


_all_slice = ...
class NamedProperty:
    def __init__(self, disp, get, put, putref) -> None:
        ...
    
    def __getitem__(self, arg):
        ...
    
    def __call__(self, *args):
        ...
    
    def __setitem__(self, name, value): # -> None:
        ...
    
    def __iter__(self):
        """Explicitly disallow iteration."""
        ...
    


class Dispatch:
    """Dynamic dispatch for an object the exposes type information.
    Binding at runtime is done via ITypeComp::Bind calls.
    """
    def __init__(self, comobj, tinfo) -> None:
        ...
    
    def QueryInterface(self, *args): # -> Any:
        "QueryInterface is forwarded to the real com object."
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __getattr__(self, name): # -> Any | NamedProperty | Callable[..., Any]:
        """Get a COM attribute."""
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    def __call__(self, *args): # -> Any:
        ...
    
    def __getitem__(self, arg): # -> Any:
        ...
    
    def __setitem__(self, name, value): # -> Any:
        ...
    
    def __iter__(self): # -> Any:
        ...
    


