"""
This type stub file was generated by pyright.
"""

from comtypes.tools.codegenerator.modulenamer import name_friendly_module, name_wrapper_module
from comtypes.tools.codegenerator.codegenerator import CodeGenerator, version

