"""
This type stub file was generated by pyright.
"""

import io
from comtypes.tools import typedesc

class ComInterfaceBodyImplCommentWriter:
    def __init__(self, stream: io.StringIO) -> None:
        ...
    
    def write(self, body: typedesc.ComInterfaceBody) -> None:
        ...
    


