"""
This type stub file was generated by pyright.
"""

import io
from typing import Optional, Sequence
from comtypes.tools import typedesc

class StructureHeadWriter:
    def __init__(self, stream: io.StringIO) -> None:
        ...
    
    def write(self, head: typedesc.StructureHead, basenames: Sequence[str]) -> None:
        ...
    


class LibraryHeadWriter:
    def __init__(self, stream: io.StringIO) -> None:
        ...
    
    def write(self, lib: typedesc.TypeLib) -> None:
        ...
    


class CoClassHeadWriter:
    def __init__(self, stream: io.StringIO, filename: Optional[str]) -> None:
        ...
    
    def write(self, coclass: typedesc.CoClass) -> None:
        ...
    


class ComInterfaceHeadWriter:
    def __init__(self, stream: io.StringIO) -> None:
        ...
    
    def write(self, head: typedesc.ComInterfaceHead, basename: str) -> None:
        ...
    


class DispInterfaceHeadWriter:
    def __init__(self, stream: io.StringIO) -> None:
        ...
    
    def write(self, head: typedesc.DispInterfaceHead, basename: str) -> None:
        ...
    


