"""
This type stub file was generated by pyright.
"""

from typing import Any, Union as _UnionT
from comtypes.tools import typedesc

class lcid:
    def __repr__(self): # -> Literal['_lcid']:
        ...
    


lcid = ...
class dispid:
    def __init__(self, memid) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class helpstring:
    def __init__(self, text) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


ctypes_names = ...
def get_real_type(tp):
    ...

ASSUME_STRINGS = ...
_DefValType = _UnionT["lcid", Any, None]
_IdlFlagType = _UnionT[str, dispid, helpstring]
class ComMethodGenerator:
    def __init__(self, m: typedesc.ComMethod, isdual: bool) -> None:
        ...
    
    def generate(self) -> str:
        ...
    


class DispMethodGenerator:
    def __init__(self, m: typedesc.DispMethod) -> None:
        ...
    
    def generate(self) -> str:
        ...
    


class DispPropertyGenerator:
    def __init__(self, m: typedesc.DispProperty) -> None:
        ...
    
    def generate(self) -> str:
        ...
    


class TypeNamer:
    def __call__(self, t: Any) -> str:
        ...
    


