"""
This type stub file was generated by pyright.
"""

from typing import Optional
from comtypes import typeinfo

def name_wrapper_module(tlib: typeinfo.ITypeLib) -> str:
    """Determine the name of a typelib wrapper module"""
    ...

def name_friendly_module(tlib: typeinfo.ITypeLib) -> Optional[str]:
    """Determine the friendly-name of a typelib module.
    If cannot get friendly-name from typelib, returns `None`.
    """
    ...

