"""
This type stub file was generated by pyright.
"""

def calc_packing(struct, fields): # -> int | None:
    ...

class PackingError(Exception):
    ...


dont_assert_size = ...
def storage(t): # -> tuple[Any | int, Any | int] | tuple[int, int]:
    ...

